export const DEFAULT_SEARCH = "DEFAULT_SEARCH";
export const DETAIL_SEARCH = "DETAIL_SEARCH";
export const SET_COMPLEX_SEARCH_KEYS = "SET_COMPLEX_SEARCH_KEYS";
export const UPDATE_COMPLEX_SEARCH_FILTERS = "UPDATE_COMPLEX_SEARCH_FILTERS";
export const UPDATE_COMPLEX_SEARCH_STRING = "UPDATE_COMPLEX_SEARCH_STRING";
export const UPDATE_COMPLEX_SEARCH_LEGACY_FILTERS = "UPDATE_COMPLEX_SEARCH_LEGACY_FILTERS";
export const UPDATE_COMPLEX_SEARCH_QUERY = "UPDATE_COMPLEX_SEARCH_QUERY";
export const SET_SEARCH_MODE = "SET_SEARCH_MODE";
